// <auto-generated />
using System;
using AgendamentoHospitalarInteligente.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendamentoHospitalarInteligente.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414223435_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Agendas", (string)null);
                });

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time");

                    b.Property<int>("MedicoAlocadoId")
                        .HasColumnType("int");

                    b.Property<string>("PacienteNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.HasIndex("MedicoAlocadoId");

                    b.ToTable("Consultas", (string)null);
                });

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.MedicoAlocado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.ToTable("MedicosAlocados", (string)null);
                });

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.MedicoModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MedicosModelo", (string)null);
                });

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.PacienteNaoAlocado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.ToTable("PacientesNaoAlocados", (string)null);
                });

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("AgendamentoHospitalarInteligente.Domain.Entities.Agenda", null)
                        .WithMany("Consultas")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgendamentoHospitalarInteligente.Domain.Entities.MedicoAlocado", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoAlocadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AgendamentoHospitalarInteligente.Domain.ValueObjects.Horario", "Horario", b1 =>
                        {
                            b1.Property<int>("ConsultaId")
                                .HasColumnType("int");

                            b1.Property<TimeOnly>("Fim")
                                .HasColumnType("time")
                                .HasColumnName("HorarioFim");

                            b1.Property<TimeOnly>("Inicio")
                                .HasColumnType("time")
                                .HasColumnName("HorarioInicio");

                            b1.HasKey("ConsultaId");

                            b1.ToTable("Consultas");

                            b1.WithOwner()
                                .HasForeignKey("ConsultaId");
                        });

                    b.Navigation("Horario")
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.MedicoAlocado", b =>
                {
                    b.HasOne("AgendamentoHospitalarInteligente.Domain.Entities.Agenda", null)
                        .WithMany("Medicos")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("AgendamentoHospitalarInteligente.Domain.ValueObjects.Horario", "HorariosDisponiveis", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("Fim")
                                .HasColumnType("time")
                                .HasColumnName("Fim");

                            b1.Property<TimeOnly>("Inicio")
                                .HasColumnType("time")
                                .HasColumnName("Inicio");

                            b1.Property<int>("MedicoAlocadoId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("MedicoAlocadoId");

                            b1.ToTable("MedicoAlocadoHorarios", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicoAlocadoId");
                        });

                    b.Navigation("HorariosDisponiveis");
                });

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.MedicoModelo", b =>
                {
                    b.OwnsMany("AgendamentoHospitalarInteligente.Domain.ValueObjects.Horario", "HorariosDisponiveis", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("Fim")
                                .HasColumnType("time")
                                .HasColumnName("Fim");

                            b1.Property<TimeOnly>("Inicio")
                                .HasColumnType("time")
                                .HasColumnName("Inicio");

                            b1.Property<int>("MedicoModeloId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("MedicoModeloId");

                            b1.ToTable("MedicoModeloHorarios", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicoModeloId");
                        });

                    b.Navigation("HorariosDisponiveis");
                });

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.PacienteNaoAlocado", b =>
                {
                    b.HasOne("AgendamentoHospitalarInteligente.Domain.Entities.Agenda", null)
                        .WithMany("PacientesNaoAlocados")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgendamentoHospitalarInteligente.Domain.Entities.Agenda", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Medicos");

                    b.Navigation("PacientesNaoAlocados");
                });
#pragma warning restore 612, 618
        }
    }
}
